apiVersion: apps/v1
kind: Deployment
metadata:
  name: spire-server
  namespace: spire
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spire-server
  template:
    metadata:
      labels:
        app: spire-server
    spec:
      serviceAccountName: spire-server
      containers:
        - name: spire-server
          image: spiretf/docker-spire-server:latest
          volumeMounts:
            - name: config
              mountPath: /opt/spire/conf
          ports:
            - containerPort: 8081
              name: grpc
      volumes:
        - name: config
          configMap:
            name: spire-server-config

