apiVersion: v1
kind: Service
metadata:
  name: distribution-service
  namespace: distribution
  labels:
    app: distribution
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
spec:
  type: ClusterIP
  selector:
    app: distribution
  ports:
    - name: http                       # HTTP communication
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: grpc                       # gRPC communication
      protocol: TCP
      port: 50053
      targetPort: 50053
    - name: metrics                    # Prometheus metrics scraping
      protocol: TCP
      port: 9100
      targetPort: 9100

