apiVersion: v1
kind: Service
metadata:
  name: logistics-service
  namespace: logistics
  labels:
    app: logistics
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
spec:
  type: ClusterIP
  selector:
    app: logistics
  ports:
    - name: http                       # HTTP communication
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: grpc                       # gRPC communication
      protocol: TCP
      port: 50054
      targetPort: 50054
    - name: metrics                    # Prometheus metrics scraping
      protocol: TCP
      port: 9100
      targetPort: 9100

